### ISSUE TITLE
Not supported to lnova 3.x

### ISSUE THREAD

**Issue by zgetro** [superlatif-io/nova-tag-input#14]
great tool, it only works with JSON datatype. 
edit mode always shows blank , ` ->allowEditTags(true)` this is not working as expeaced.

**Comment by abishekrsrikaanth** [comment]
Same issue, but doesn't work with JSON data type as well. It saves the data but doesn't show the data on edit mode./

**Comment by superlatif-io** [comment]
Hi guys,

could you provide me the code of how you implemented the tool? Specifically your Nova resource, Model, migration file with the field storing the tags and also a screenshot of the saved data in your database.

Thanks

**Comment by abishekrsrikaanth** [comment]
@superlatif-io, on Nova version 3.27.0

**Code on the Resource fields**

```
Tags::make('Tags')
                ->allowEditTags()
```

The table is setup with a `VARCHAR(255)` datatype and below is the data that is stored on the DB.

<img width="181" alt="Tags Issue" src="https://user-images.githubusercontent.com/1639302/125650557-eeaae3f2-d24b-4570-b6e4-5a9ebfa4a0d3.png">

I have tried with both `string` and `json` columns and both don't work.

**Comment by vFire** [comment]
same thing
