### ISSUE TITLE
Tag input stores unwanted data

### ISSUE THREAD

**Issue by bernhardh** [superlatif-io/nova-tag-input#2]
Hello and thank you for your great package.

Is it the expected behaviour, that your tag input stores not only the tags, but also a weird data structure like this, when adding the two word `test1` and `test2` to a tag input:

```json
[{"text":"test1","tiClasses":["ti-valid"]},{"text":"test2","tiClasses":["ti-valid"]}]
```

Thats not only a waste of database/ram space but it also make it harder to use it outside of nova. Or is it just an error from my side?

**Comment by superlatif-io** [comment]
Hi @bernhardh,

thank you for your message, yes this is coming from the underlying JS plugin which is using this structure for data validation, I too think this could be optimized and I will look into a less dependant way to store the data in DB.

**Comment by superlatif-io** [comment]
Done :-)

**Comment by msouto346** [comment]
> Done :-)

Hello @superlatif-io, what do you mean by done? I am trying your package and getting the same problem.
