### ISSUE TITLE
Can't store tags in database

### ISSUE THREAD

**Issue by AndrewMelnikow** [superlatif-io/nova-tag-input#3]
Hello, I can't store tags into my database.
I have an error: **Array to string conversion** on click "Update Resource" button

I have installed package via _composer require superlatif/nova-tag-input_
Next, I added use Superlatif\NovaTagInput\Tags; to my Resource
And then added this code to create field:
 ```
 Tags::make('Keywords', 'keywords')
                    ->help("Press ENTER to add keyword")
                    ->placeholder("Add a new keyword")
                    ->allowEditTags(true)
```

Why it's not working?

**Comment by superlatif-io** [comment]
Hi @AndrewMelnikow,

Did you set the correct attribute casting in your model? Your keywords attribute should be cast to array, you can check the Laravel documentation about this here:

https://laravel.com/docs/6.x/eloquent-mutators#array-and-json-casting

**Comment by AndrewMelnikow** [comment]
@superlatif-io This helped me, thank you very much!

**Comment by mostyn-grp** [comment]
This error shows if the tags input is empty
