### ISSUE TITLE
Pasting with comma doesn't split the tags

### ISSUE THREAD

**Issue by abishekrsrikaanth** [superlatif-io/nova-tag-input#8]
I have the `addOnKeys` set to `[13, ',']`. But when pasting content with comma doesn't split the tags when they are added to the field. Is there a way to do this?

**Comment by superlatif-io** [comment]
Hi,

yes you should use the **_separators()_** parameter when you want to split some pasted text into tags, it uses ";" by default but accepts an array of characters.

This parameter was missing from the readme file unfortunately, you can use it like so:

->separators([';', ','])
